/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import CapaNegocio.nReporte;
import java.io.File;

import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author david
 */
public class iuReportes extends javax.swing.JInternalFrame {

    /**
     * Creates new form iuReportes
     */
    public iuReportes() {
        ((JPanel)getContentPane()).setOpaque(fal­se);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/Archivo/fondo.jpg"));
        JLabel fondo= new JLabel(); 
        fondo.setIcon(uno); 
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER); 
        fondo.setBounds(0,0,uno.getIconWidth(),u­no.getIconHeight());
        initComponents();
      
        this.setTitle("Generar Reportes");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSolicitud = new javax.swing.JButton();
        btnChofer = new javax.swing.JButton();
        btnMantenimiento = new javax.swing.JButton();
        btnEstacionamiento = new javax.swing.JButton();
        btnVehiculo = new javax.swing.JButton();
        txtSolicitud = new javax.swing.JTextField();
        txtMantenimiento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Generar Reportes"));
        jPanel1.setOpaque(false);

        btnSolicitud.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivo/documento.png"))); // NOI18N
        btnSolicitud.setText("Solicitudes");
        btnSolicitud.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSolicitud.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitudActionPerformed(evt);
            }
        });

        btnChofer.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnChofer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivo/chofer.png"))); // NOI18N
        btnChofer.setText("Chofer");
        btnChofer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChofer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoferActionPerformed(evt);
            }
        });

        btnMantenimiento.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivo/cog1.png"))); // NOI18N
        btnMantenimiento.setText("Mantenimiento");
        btnMantenimiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMantenimiento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoActionPerformed(evt);
            }
        });

        btnEstacionamiento.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnEstacionamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivo/estacionamiento.png"))); // NOI18N
        btnEstacionamiento.setText("Estacionamiento");
        btnEstacionamiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEstacionamiento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEstacionamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstacionamientoActionPerformed(evt);
            }
        });

        btnVehiculo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivo/gandola.png"))); // NOI18N
        btnVehiculo.setText("Vehiculos");
        btnVehiculo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVehiculo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculoActionPerformed(evt);
            }
        });

        txtSolicitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSolicitudKeyTyped(evt);
            }
        });

        jLabel1.setText("Ingrese N# Solicitud");

        jLabel2.setText("Ingrese la placa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnChofer, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnEstacionamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChofer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnEstacionamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitudActionPerformed
if(!txtSolicitud.getText().equals("")){
        nReporte func=new nReporte();
        Map p=new  HashMap();//eviar un parametro reporte
        p.put("Numero_solicitud", txtSolicitud.getText());
       JasperReport report;
       JasperPrint print;
       
        try {
            report=JasperCompileManager.compileReport(new File("").getAbsolutePath()+"/src/Reportes/rpSolicitud.jrxml");
            print=JasperFillManager.fillReport(report, p, func.getConnection());
            JasperViewer view=new JasperViewer(print,false);
            view.setTitle("Detalles de Solicitud");
            view.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        
}
else {
         JOptionPane.showMessageDialog(this, "El campo de texto esta vacio, ingrese el numero de solicitud de un cliente");
     }
    }//GEN-LAST:event_btnSolicitudActionPerformed

    private void btnChoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoferActionPerformed
     nReporte func=new nReporte();
        Map p=new  HashMap();//eviar un parametro reporte
       JasperReport report;
       JasperPrint print;
       
        try {
            report=JasperCompileManager.compileReport(new File("").getAbsolutePath()+"/src/Reportes/rpChofer.jrxml");
            print=JasperFillManager.fillReport(report, p, func.getConnection());
           JasperViewer view=new JasperViewer(print,false);
           view.setTitle("Reportes de Choferes");
           view.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
       
    }//GEN-LAST:event_btnChoferActionPerformed

    private void btnMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoActionPerformed
     if(!txtMantenimiento.getText().equals("")){
        nReporte func=new nReporte();
        Map p=new  HashMap();//eviar un parametro reporte
        p.put("Placa", txtMantenimiento.getText());
       JasperReport report;
       JasperPrint print;
       
        try {
            report=JasperCompileManager.compileReport(new File("").getAbsolutePath()+"/src/Reportes/rpMantenimiento.jrxml");
            print=JasperFillManager.fillReport(report, p, func.getConnection());
            JasperViewer view=new JasperViewer(print,false);
            view.setTitle("Historial de mantenimiento");
            view.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        

    }  
     else {
         JOptionPane.showMessageDialog(this, "El campo de texto esta vacio, ingrese la placa de una gandola");
     }
    }//GEN-LAST:event_btnMantenimientoActionPerformed

    private void btnEstacionamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstacionamientoActionPerformed
 nReporte func=new nReporte();
        Map p=new  HashMap();//eviar un parametro reporte
       JasperReport report;
       JasperPrint print;
       
        try {
            report=JasperCompileManager.compileReport(new File("").getAbsolutePath()+"/src/Reportes/rpEstacionamiento.jrxml");
            print=JasperFillManager.fillReport(report, p, func.getConnection());
           JasperViewer view=new JasperViewer(print,false);
           view.setTitle("Reportes de Estacionamientos");
           view.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
       
        
    }//GEN-LAST:event_btnEstacionamientoActionPerformed

    private void btnVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculoActionPerformed
       nReporte func=new nReporte();
        Map p=new  HashMap();//eviar un parametro reporte
       JasperReport report;
       JasperPrint print;
       
        try {
            report=JasperCompileManager.compileReport(new File("").getAbsolutePath()+"/src/Reportes/rpVehiculo.jrxml");
            print=JasperFillManager.fillReport(report, p, func.getConnection());
           JasperViewer view=new JasperViewer(print,false);
           view.setTitle("Reportes de Vehiculos");
           view.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
       
        
                                   
    }//GEN-LAST:event_btnVehiculoActionPerformed

    private void txtSolicitudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSolicitudKeyTyped
      char c=evt.getKeyChar();
          if(Character.isLetter(c)) {
              getToolkit().beep(); 
              evt.consume(); 
              JOptionPane.showMessageDialog(null, "Debe ingresar solo numeros");
    }    

    }//GEN-LAST:event_txtSolicitudKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iuReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iuReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iuReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iuReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new iuReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChofer;
    private javax.swing.JButton btnEstacionamiento;
    private javax.swing.JButton btnMantenimiento;
    private javax.swing.JButton btnSolicitud;
    private javax.swing.JButton btnVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtMantenimiento;
    private javax.swing.JTextField txtSolicitud;
    // End of variables declaration//GEN-END:variables
}
